namespace Minecraft.Messages;

/// <summary>
///     Represents a click action.
/// </summary>
public enum ClickAction
{
    /// <summary> The click action if OpenUrl. </summary>
    /// <remarks>
    ///     Opens <see cref="ClickEvent.Value"/> as a URL in the user's default web browser.
    /// </remarks>
    OpenUrl,

    /// <summary> The click action if OpenFile. </summary>
    /// <remarks>
    ///     Opens the file at <see cref="ClickEvent.Value"/> on the user's computer.
    ///     This is used in messages automatically generated by the game
    ///     (e.g., on taking a screenshot) and cannot be used by players for security reasons.
    /// </remarks>
    OpenFile,

    /// <summary> The click action if RunCommand. </summary>
    /// <remarks>
    ///     Works in signs, but only on the root text component, not on any children.
    ///     Activated by using the sign. In chat and written books, this has <see cref="ClickEvent.Value"/>
    ///     entered in chat as though the player typed it themselves and pressed enter.
    ///     However, this can only be used to run commands that do not send chat messages directly
    ///     (like /say, /tell, and /teammsg). Since they are being run from chat, commands must be
    ///     prefixed with the usual "/" slash, and player must have the required permissions.
    ///     In signs, the command is run by the server at the sign's location, with the player
    ///     who used the sign as the command executor (that is, the entity selected by @s).
    ///     Since they are run by the server, sign commands have the same permission level
    ///     as a command block instead of using the player's permission level, are not restricted
    ///     by chat length limits, and do not need to be prefixed with a "/" slash.
    /// </remarks>
    RunCommand,

    /// <summary> The click action if SuggestCommand. </summary>
    /// <remarks>
    ///     Opens chat and fills in <see cref="ClickEvent.Value"/>.
    ///     If a chat message was already being composed, it is overwritten. This does not work in books.
    /// </remarks>
    SuggestCommand,

    /// <summary> The click action if ChangePage. </summary>
    /// <remarks>
    ///     Can only be used in written books. Changes to page <see cref="ClickEvent.Value"/> if that page exists.
    /// </remarks>
    ChangePage,

    /// <summary> The click action if CopyToClipboard. </summary>
    /// <remarks>
    ///     Copies <see cref="ClickEvent.Value"/> to the clipboard.
    /// </remarks>
    CopyToClipboard
}
