name: Build

on:
  workflow_call:
    inputs:
      target:
        description: 'Targeting OS'
        required: true
        type: string
      dotnet-version:
        description: '.NET version'
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.target }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Restore Dependencies
        run: dotnet restore src

      - name: Build
        run: dotnet build src --no-restore
