name: Kook.Net on Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        target: [ windows-latest, ubuntu-latest, macOS-latest ]
    uses: ./.github/workflows/build.yml
    with:
      target: ${{ matrix.target }}
      dotnet-version: 7.0.x
